# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 284f3c78ec84a52c1bed05a1defdd3a160fb51e9964258bf8d384d9dde755a7ab6f118977c677de380ec86e5801fd0c2fbcd7e54ab9e6649a7d7401854612c47

test:
  secret_key_base: 8f2a0636e8423918d31cd05728f8ef6c6be7dcfb1bf318c31a20f27b77e57a67a8670517dc7a06613a2343638b61200f366b3307de38a35ba95dade8e911600c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
